# baseURL: http://example.org/
baseURL: https://moonlit-brigadeiros-6f6843.netlify.app/
languageCode: en-us
title: Yogesh Singh Nayal
# baseURL: "https://hugo-profile.netlify.app"
# languageCode: "en-us"
# title: "Hugo Profile"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

    # Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  # title: "Hugo Profile"
  title: "Yogesh Singh Nayal"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav2.jpg"
  # favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Yogesh."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /images/Yogesh3.jpg
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1AiNhoCut3K6ZBNuTHBcIdTR2ygf0PiQa/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          # url: https://example.com
          url: https://github.com/ysnayal17
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/yogesh-singh-nayal-150326178/
        # - icon: fab fa-twitter
        #   url: https://twitter.com/YogeshSinghNay5
      customIcons:
        # - icon: /fav.png
        - icon: /fav2.jpg
          # url: "https://example.com"
          url: "#"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/Yogesh2.jpg"
    content: |-
      I am a software developer, currently pursuing degree in B-Tech from St. Francis Institute of Technology. Also I am a web developer intern at [Sparks Foundation](https://www.thesparksfoundationsingapore.org/). Previously I worked as a machine learning intern at [GRROOM](https://grroom.in/). I have strong passion in technology.

      My goal is to become a best software developer so that I could be helpful in catering people's wishes with regards to technology.
    # content: |-
    #   I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

    #   I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - title: "HTML/CSS"
          url: "https://drive.google.com/file/d/1od2ypXgiI6dPSCBA4kPKtRymnpVWBu4e/view?usp=sharing"
        - title: "JavaScript"
          url: "https://drive.google.com/file/d/1QNoPAFRqCyBNth18xybRD1lWxi3ly-Nv/view?usp=sharing"
        - title: "React"
          url: "#"
        - title: "Node"
          url: "#"
        - title: "Python"
          url: "https://drive.google.com/file/d/1lTXZi02qHkd8Qm8Lxz1iFBYcpgKxCbRO/view?usp=sharing"
        - title: "Django"
          url: "#"
        - title: "Machine Learning"
          url: "https://drive.google.com/file/d/1mh79ZMShv0eXROq6hLfYpHjokLZd8WJR/view?usp=sharing"
        - title: "Data Science"
          url: "https://drive.google.com/file/d/1NdCi61e9Dvk_1rEnQ5XvHQiD89A4-bQu/view?usp=sharing"
        - title: "DEV-OPS"
          url: "https://drive.google.com/file/d/1AhNIQZhr4zzN9neGjlumyqQsyvnCTFTC/view?usp=sharing"
        - title: "Blockchain"
          url: "#"
        - title: "Git/Github"
          url: "https://drive.google.com/file/d/1BFGQ9o7YjNmZVUcy65n9UbfCnsjmnoiL/view?usp=sharing"
        - title: "Ethical Hacking"
          url: "https://drive.google.com/file/d/1I32tYXpRFjUR854sx6Vc2rpbez4cV4HU/view?usp=sharing"
        # - "JavaScript"
        # - "React"
        # - "Node"
        # - "Python"
        # - "Django"
        # - "Machine Learning"
        # - "Deep Learning"
        # - "Blockchain"

  # Experience
  experience:
    enable: true
    items:
      - job: "Web Developer Intern"
        company: "Sparks Foundation"
        companyUrl: "https://www.thesparksfoundationsingapore.org"
        date: "Jul 2022 - present"
        featuredLink:
          enable: true
          # name: "View the project"
          name: "Certificate"
          url: "https://drive.google.com/file/d/1ylq4XGfp4bNuqtRWNpgmGHAEM9oVi8rF/view?usp=sharing"
        content: "I am currently working as a web developer intern at [Sparks Foundation](https://www.thesparksfoundationsingapore.org). Here my project will be based on React Frontend Framework."

      - job: "Machine Learning Intern"
        company: "Grroom"
        companyUrl: "https://grroom.in/"
        date: "28th Aug 2021 - 28th Oct 2021"
        featuredLink:
          enable: true
          name: "Certificate/LOR"
          url: "https://drive.google.com/file/d/10nUvYfYW0Mu0nyezXVsgfY_HKqwz7Vsn/view?usp=sharing"
        info:
          enable: true
          content: I worked as a machine learning intern for around 2 months in GRROOM.
        content: |
          I worked as a machine learning intern at [GRROOM](https://grroom.in/). I worked on web scraping, model training, model testing. I worked towards communicating and managing other team members. I managed to provide them with unique solutions and has completed the assignments allotted to me on time with perfection.

      # - job: "Junior Software Developer"
      #   company: "Apple"
      #   companyUrl: "https://example.com"
      #   date: "Jan 2020 - Aug 2020"
      #   info:
      #     enable: false
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelors in Technology"
        school:
          name: "Mumbai University, St. Francis Institute of Technology"
          url: "https://www.sfit.ac.in/"
        date: "2019 - 2023"
        GPA: "9.4 out of 10"
        # content: |-
        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "12th- PCM + Computer Science (CBSE)"
        school:
          name: "Kendriya Vidyalaya No.2, Colaba"
          url: "https://no2colaba.kvs.ac.in/"
        date: "2018-2019"
        GPA: "91.4% out of 100"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "10th- Science (CBSE)"
        school:
          name: "Kendriya Vidyalaya No.2, Colaba"
          url: "https://no2colaba.kvs.ac.in/"
        date: "2016-2017"
        GPA: "10 out of 10"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      # - title: Google kickstart runner
      #   content: I solved all problems with optimal solution.
      #   url: https://example.com
      - title: Codexpress 5.0 
        content: I acquired 2nd place in my college in this coding competition.
        url: https://drive.google.com/file/d/1USOr_G9nnX3bvHDS00MpOFwG9ZCgazqm/view?usp=sharing
      - title: DEV-OPS Course
        content: Obtained A Grade in 30hrs value added course on DEV-OPS.
        url: https://drive.google.com/file/d/1AhNIQZhr4zzN9neGjlumyqQsyvnCTFTC/view?usp=sharing
      - title: Hacktober Fest 2020
        content: Successfully contributed to open source projects worldwide.
        url: https://www.linkedin.com/posts/yogesh-singh-nayal-150326178_hacktoberfest2020-hacktoberfest-digitalocean-activity-6751776761928855552-LIim?utm_source=linkedin_share&utm_medium=member_desktop_web
      - title: JEE MAINS 
        content: Secured 95.14 percentile in JEE Mains April 2019 session.
        url: "https://drive.google.com/file/d/12VGKwFVWWsMosyXj3O_xZxp8l9AzFy2y/view?usp=sharing"
      - title: Cricket 
        content: Represented Mumbai region in cricket U-17 held in Chennai
        url: "https://drive.google.com/file/d/1ANmpgnmbl_1oLR-PJmbWN93WMZwhiYWE/view?usp=sharing"

  # projects
  projects:
    enable: true
    items:
      - title: Stock Prediction Using Twitter Sentiment Analysis
        content: Web Application that predicts stock price and stock trend of a company depending on the tweets sentiments of that company. Used LSTM model for price prediction whereas TextBlob library for twitter sentiments.
        image: /images/projects/project1.png
        # featured:
        #   name: Demo
        #   link: https://github.com/ysnayal17/Sem6-project
        badges:
          - "Deep Learning/ML"
          - "Django"
          - "Bootstrap"

        links:
          # - icon: fa fa-envelope
          #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/ysnayal17/Sem6-project
          # - icon: fab fa-twitter
          #   url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: CLASSMEET- Virtual Classroom
        content: Web application using which teachers and students could collaborate virtually. The web application was build using Django Framework.
        image: /images/projects/project2.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/ysnayal17/CLASSMEET

      - title: List Shopping Item
        content: Ability to add items for shopping and as in when the item is bought changing it's status are some crucial aspect of this simple web app.
        image: /images/projects/project3.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/ysnayal17/List-Shopping-Items

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: ysnayal17@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/ysnayal17
      linkedin: https://www.linkedin.com/in/yogesh-singh-nayal-150326178/
      twitter: https://twitter.com/YogeshSinghNay5
      instagram: https://www.instagram.com/ysnayal_17/
      facebook: https://www.facebook.com/yogesh.singhnayal.7
